FROM ubuntu:20.04 AS cpp
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
	build-essential \
	cmake  \
	libicu-dev \
	git \
	wget \
	p7zip-full \
	&& rm -rf /var/lib/apt/lists/* \
	&& mkdir /src

FROM cpp AS cppBoost
LABEL description="C++ build with boost-test"
RUN apt-get update && apt-get install -y ca-certificates \
	&& cd /src \
	&& mkdir ./ExternalDependencies \
	&& git clone https://github.com/glen-summers/BoostModularBuild.git \
	&& ./BoostModularBuild/go.sh build test \
	&& rm -r ./BoostModularBuild

FROM cppBoost as GLib
LABEL description="GLib"
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y locales dos2unix \
	&& locale-gen en_GB.UTF-8 \
	&& update-locale LANG=en_GB.UTF-8
ENV LANG en_GB.UTF-8
ARG dir=/src/GLib
RUN mkdir -p $dir
COPY /go.sh $dir
COPY /CMakeLists.txt $dir
COPY /cmake $dir/cmake
COPY /GLib $dir/GLib
COPY /include $dir/include
COPY /Tests $dir/Tests
COPY /Coverage/CppHtmlGenerator.h $dir/Coverage/CppHtmlGenerator.h
COPY /Coverage/SymbolNameUtils.h $dir/Coverage/SymbolNameUtils.h
CMD ["/bin/bash"]