FROM ubuntu:21.10 AS cpp
LABEL description="C++ utils etc."
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
	ca-certificates \
	build-essential \
	gcc-11 g++-11 \
	cmake \
	libicu-dev \
	lcov \
	git \
	wget \
	p7zip-full \
	&& rm -rf /var/lib/apt/lists/*

FROM cpp AS glib-boost
LABEL description="C++ build with boost-test"
ENV HOME /src
RUN mkdir -p ${HOME}/tmp ${HOME}/ExternalDependencies \
	&& git clone https://github.com/glen-summers/BoostModularBuild.git ${HOME}/tmp \
	&& ${HOME}/tmp/go.sh build test \
	&& rm -r ${HOME}/tmp

FROM glib-boost AS glib
LABEL description="GLib source"
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y locales dos2unix \
	&& locale-gen en_GB.UTF-8 \
	&& update-locale LANG=en_GB.UTF-8
ENV LANG en_GB.UTF-8
ARG dir=${HOME}/GLib
RUN mkdir -p $dir
COPY /boost.version $dir
COPY /go.sh $dir
COPY /CMakeLists.txt $dir
COPY /cmake $dir/cmake
COPY /GLib $dir/GLib
COPY /include $dir/include
COPY /Tests $dir/Tests
COPY /Coverage/SymbolNameUtils.h $dir/Coverage/
RUN ${HOME}/GLib/go.sh
CMD ["/bin/bash"]

FROM glib AS glib-coverage
LABEL description="GLib Coverage Build"
RUN ${HOME}/GLib/go.sh coverage
CMD ["/bin/bash"]